apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-nginx-manual
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab-nginx-manual
  template:
    metadata:
      labels:
        app: lab-nginx-manual
    spec:
      containers:
        - name: nginx
          image: nginx:1.25