apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: conversao-temp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/RangelCR/conversao-temperatura.git
    path: k8s
    targetRevision: HEAD
  destination:
    server: https://43902f24-b51c-4e1a-a58f-2ef2b4a86cd8.k8s.ondigitalocean.com
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
