apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tasks
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/RangelCR/tasks.git
    path: k8s/
    targetRevision: HEAD
    directory:
      recurse: true      
  destination:
    server: https://kubernetes.default.svc
    namespace: hml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true